# Generated by Django 5.0.3 on 2024-03-21 15:43

import capital_calls.validators.due_date
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iban', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_first_investment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(validators=[capital_calls.validators.due_date.validate_due_date_gt_today])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=10)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls', to='capital_calls.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('membership', 'Membership'), ('upfront', 'Upfront'), ('yearly', 'Yearly')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('capital_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='capital_calls.capitalcall')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='capital_calls.investor')),
            ],
        ),
    ]
